<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>14</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0</FileVersion>
    <Version>1.0.0</Version>
    <Description>FluidPDF template engine using Scriban</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Scriban" Version="7.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FluidPDF\FluidPDF.csproj" />
  </ItemGroup>

</Project>
